const TAB_CLICKED = 'TAB_CLICKED';
const ADD_PRODUCT = 'ADD_PRODUCT';
const ADD_TO_CART = 'ADD_TO_CART';
const ADD_TO_HISTORY = 'ADD_TO_HISTORY';

export {TAB_CLICKED, ADD_PRODUCT, ADD_TO_CART, ADD_TO_HISTORY};
